repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: name-tests-test
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
